### ISSUE TITLE
关闭Dopamine的同时会关闭其他cmd进程

### ISSUE THREAD

**Issue by litev4** [litev4/Dopamine#1]
Windows 版本: Windows 11 23H2(build 22631.4037)
Dopamine 版本: v1.0 alpha
希沃管家版本: 1.4.9.3649
BUG复现过程：
1.打开Dopamine
2.打开cmd.exe
3.关闭Dopamine
4.先前打开的cmd.exe也被关闭了

**Comment by litev4** [comment]
如果这个issue没关就是还没修好（
实在想不到方法去修这个bug（（

**Comment by SeriesNotFound** [comment]
可以尝试使用以下的方法来获取PID, 并将其写入文件中
tasklist /v /fo csv | findstr /i "Dopamine Service." ＞ randomName.txt

然后负责结束的进程读取此文件, 用
taskkill /f /pid ＜读取到的PID＞
来做单进程的进程终止

最后代码中一直循环检查进程的行为可能会造成大量的CPU占用, 考虑加个延时（

**Comment by litev4** [comment]
感谢你提供的解决方案，下面我来回答CPU占用的问题:

循环检查进程其实并不会造成大量的CPU占用，在我的Ryzen 7 5800H上几乎没有占用，以及在Intel Pentium 4415U上的CPU占用也只有0.5%~1.0%，如果只是考虑给希沃白板使用的话已经足够了。
我这里大多数白板都搭载的是以下的CPU：
1.Intel i5-2310M CPU
2.Intel i3-8100 CPU
3.Intel i5-8400 CPU
以上三款CPU都比Intel Pentium 4415U的性能高了，况且Dopamine在4415U的表现情况也不错，所以没有必要再进行进一步的优化。

最后还是感谢，你的方案将会在明天进行验证可行性后进行使用。

**Comment by litev4** [comment]
![QQ_1724430931976](https://github.com/user-attachments/assets/436fb0e1-1c3f-4369-8f45-a9f362cc05d9)
感觉可以试试，我可能会熬夜实现一下这个功能

**Comment by litev4** [comment]
![QQ_1724431702761](https://github.com/user-attachments/assets/bdf6ba40-e95e-4528-8ce8-810c4dd35cfe)
我找了另外的方案，但还是感谢你的思路！
更新版本稍后会放出！
